#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# Converts OpenRM binhex-encoded images to Nova-compatible binary blobs.
#
# Requires pcpp (packaged as python3-pcpp on Debian and Ubuntu, and as pcpp on PyPI) to
# preprocess the RM headers that constants are read from, and to evaluate the C constant
# expressions that appear in those headers and in the autogenerated NVOC Hal field tables.

import sys
import os
import argparse
import copy
import glob
import re
import struct
import tempfile
import urllib.request
import shutil

try:
    from pcpp import Action, Evaluator, OutputDirective, Preprocessor
except ImportError:
    print("Error: python3-pcpp package is not installed", file=sys.stderr)
    sys.exit(1)

# Locate the shared helper module relative to this script (not the current
# working directory), so that the script can be run from anywhere.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extract_firmware_common import (
    MyException,
    get_bytes,
    is_supported,
    symlink,
    extract_run_file,
    round_up_to_base,
)

# Where all the files will be written
outputpath = ""

# Version string
version = ""

# Newer firmware versions that Nova will support might have new files
# that conflict with the symlinks for older firmware versions that
# Nouveau supports.  To avoid these collisions, support placing all Nova
# images in a new subdirectory.  The hierarchy looks like this:
#
# /lib/firmware/nvidia/{nvidiadir}/{gpu}/{subdir}/
#
# Command-line parameters can be used to override both path names.
#
# By default, this script creates a Nouveau-compatible hierarchy:
# /lib/firmware/nvidia/{gpu}/gsp/

# Top-level directory under "/lib/firmware/nvidia".
nvidiadir = ""

# Subdirectory name under the GPU name.
subdir = "gsp"

# List of all supported GPUs.  This hard-coded list is for the earliest
# GSP-RM version supported (r570).  Additional GPUs are added at runtime.
# This array is used to make sure that the files for all supported GPUs
# are present and correct.
supported = [
    "tu102",
    "tu104",
    "tu106",
    "tu116",
    "tu117",
    "ga100",
    "ga102",
    "ga103",
    "ga104",
    "ga106",
    "ga107",
    "ad102",
    "ad103",
    "ad104",
    "ad106",
    "ad107",
    "gh100",
    "gb100",
    "gb102",
    "gb202",
    "gb203",
    "gb205",
    "gb206",
    "gb207"
]

# The HAL variables Nova needs, and the gsp.tlv tag each one is written as.  gsp.tlv
# entries are written in this order, and symlinks() reads them back to check that every
# GPU ended up with the values that were computed for it.
hal_tlv_tags = {
    "HBSZ": "gspFwHeapBaseSize",
    "HSPG": "gspFwHeapSizePerGb",
    "HBSV": "gspFwHeapBaseSizeVgpu",
    "HSPV": "gspFwHeapSizePerVm",
    "PRSZ": "pmuReservedSize",
    "PWSZ": "pmuNonWprReservedSize",
}

# The value each of those variables has on each GPU, filled in at runtime.
hals = {field: {} for field in hal_tlv_tags.values()}

# -------------------------------------------------------------------
# Build tag-length-value (TLV) list
# -------------------------------------------------------------------

class TLV:
    def __init__(self, filename: str, gpu: str):
        self.filename = filename
        self.gpu = gpu
        self.entries = []

    def add(self, tag: str, value):
        filename = os.path.join(self.gpu, subdir, f"{self.filename}.tlv")

        if len(tag) != 4:
            raise MyException(f"TLV tag '{tag}' in {filename} must be exactly 4 characters")

        if any(t == tag for t, _ in self.entries):
            raise MyException(f"TLV tag '{tag}' in {filename} already exists")

        # Integers are a special case, as they have no "length" in Python
        if isinstance(value, int):
            # Reject negative numbers and integers larger than 64-bit
            if not 0 <= value <= 0xFFFFFFFFFFFFFFFF:
                raise MyException(f"TLV tag '{tag}' in {filename} integer value {value} out of range")
        else:
            if len(value) == 0:
                raise MyException(f"TLV tag '{tag}' in {filename} has no data")
            # We don't want non-ASCII strings anywhere
            if isinstance(value, str) and not value.isascii():
                raise MyException(f"TLV tag '{tag}' in {filename} value is a string but contains non-ASCII characters")

        self.entries.append((tag, value))

    def write(self):
        global outputpath
        global version

        # Add the version last so that it's not iterated over every time
        self.add("VERS", version)

        print(f"Creating {os.path.join('nvidia', nvidiadir, self.gpu, subdir, f'{self.filename}.tlv')}")
        os.makedirs(os.path.join(outputpath, "nvidia", nvidiadir, self.gpu, subdir), exist_ok = True)

        with open(os.path.join(outputpath, "nvidia", nvidiadir, self.gpu, subdir,
                               f"{self.filename}.tlv"), "wb") as f:
            f.write(struct.pack("4s", b"NVFW"))

            for tag, value in self.entries:
                # Convert strings and integers into bytearrays
                if isinstance(value, str):
                    # TLV strings are not null-terminated.
                    value = value.encode("ascii")
                elif isinstance(value, int):
                    # Support 32-bit and 64-bit integers
                    value = struct.pack("<I" if value < 0x100000000 else "<Q", value)

                f.write(struct.pack("<4sI", tag.encode("ascii"), len(value)))
                f.write(value)
                # Add padding bytes if necessary
                f.write(b"\x00" * ((-len(value)) % 4))

# Read a .tlv file back and return a dictionary of its entries.  Nothing in the file says
# whether an entry is an integer, a string or a blob, so every value is returned as raw
# bytes and the caller interprets it.
def read_tlv(filename: str) -> dict:
    with open(filename, "rb") as f:
        data = f.read()

    if data[:4] != b"NVFW":
        raise MyException(f"{filename} does not start with the 'NVFW' signature")

    entries = {}
    offset = 4

    while offset < len(data):
        if offset + 8 > len(data):
            raise MyException(f"{filename} is truncated in a TLV header")

        tag, length = struct.unpack_from("<4sI", data, offset)
        offset += 8

        # Entries are padded out to a four-byte boundary
        if offset + length > len(data):
            raise MyException(f"{filename} is truncated in the '{tag.decode('ascii')}' entry")

        entries[tag.decode("ascii")] = data[offset:offset + length]
        offset += length + ((-length) % 4)

    return entries

# -------------------------------------------------------------------
# Read ELF images
# -------------------------------------------------------------------

class ELF64:
    EI_NIDENT = 16
    ELF_MAGIC = b"\x7fELF"
    ELFCLASS64 = 2

    def __init__(self, filename: str):
        self.filename = filename
        with open(filename, "rb") as f:
            data = f.read()

        if len(data) < self.EI_NIDENT:
            raise MyException(f"{filename}: file too small to be an ELF image")

        if data[:4] != self.ELF_MAGIC:
            raise MyException(f"{filename}: not an ELF file")

        if data[4] != self.ELFCLASS64:
            raise MyException(f"{filename}: not a 64-bit ELF file")

        if data[5] != 1:
            raise MyException(f"{filename}: big-endian ELF files are not supported")

        (e_shoff, e_shentsize, e_shnum, e_shstrndx) = struct.unpack_from("<Q10xHHH", data, 0x28)

        shstrtab_off = struct.unpack_from("<24xQ", data,
            e_shoff + e_shstrndx * e_shentsize)[0]

        self.sections = []
        for i in range(e_shnum):
            sh = e_shoff + i * e_shentsize
            (sh_name, sh_offset, sh_size) = struct.unpack_from("<I20xQQ", data, sh)

            name_start = shstrtab_off + sh_name
            name_end = data.index(b"\x00", name_start)
            name = data[name_start:name_end].decode("ascii")

            # We only care about sections that start with ".fw"
            if name.startswith(".fw"):
                self.sections.append((name, data[sh_offset:sh_offset + sh_size]))

            # as well as the ".note.gnu.build-id" section
            if name == ".note.gnu.build-id":
                self.sections.append((name, data[sh_offset:sh_offset + sh_size]))

    def section(self, name: str) -> bytes:
        for sec_name, sec_data in self.sections:
            if sec_name == name:
                return sec_data
        raise MyException(f"ELF {self.filename} does not have a {name} section")

# -------------------------------------------------------------------
# Parse autogenerated NVOC HAL variables
# -------------------------------------------------------------------

# RM autogenerates per-chip "Hal field" assignments in files such as g_gpu_arch_nvoc.c.
# Each field is initialized with an if / else-if / else chain, where every if-branch
# annotates its (possibly multi-line) condition with a "/* ChipHal: GPU1 | GPU2 | ... */"
# comment listing the GPUs the branch applies to, and the trailing else is a catch-all
# default.  Fields that do not vary by chip are instead assigned unconditionally, with no
# if / else chain.  This parses one such field and returns a dictionary mapping each GPU
# name (as it appears in the comment, e.g. "TU102") to the value expression assigned for
# that GPU.  The catch-all default value is stored under the None key.

# pcpp's evaluator holds no state between calls, so one instance serves every call.  It
# returns an int subclass that additionally tracks whether the value is unsigned.
c_expression_evaluator = Evaluator()

# Parse a C integer constant expression and return its value.  Handles plain constants,
# hex ("0x..."), and arbitrary arithmetic, bitwise, and conditional expressions, such as
# "((22U << 20) + (32U << 20) + ((48U << 10) * 2048U))" or the expansion of an NV_MAX,
# "(((17485824) > (17482752)) ? (17485824) : (17482752)) + 4096U".  Every name in the
# expression must already be expanded, apart from the NvBool constants handled below.
def parse_c_value(value: str) -> int | bool:
    # Make a guess as to whether the expression is boolean or not.  This is imperfect,
    # and may need to be changed for future versions of OpenRM, because booleans and
    # integers are interchangeable in C.  For now, assume that any expression with
    # boolean macros in it is also boolean.  This breaks on ternary expressions like
    # "NV_TRUE ? x : y" however.
    is_bool = any(s in value for s in ("(NvBool)", "NV_TRUE", "NV_FALSE"))
    expression = value.replace("(NvBool)", "")

    try:
        result = c_expression_evaluator(expression,
                                        identifiers = {"NV_TRUE": 1, "NV_FALSE": 0}).value()
    except SyntaxError as e:
        raise MyException(f"Cannot evaluate C expression '{value}': {e}")

    # This should catch expressions where we miscalculate is_bool.
    if is_bool and result not in (0, 1):
        raise MyException(f"Invalid boolean expression '{value}'")

    return bool(result) if is_bool else result

# Walk the brace-delimited branch bodies of the single if / else-if / else statement that
# begins at 'start' and return the offset just past its final '}'.  The chain continues
# only while a closing brace is followed by another "else".  Branch conditions contain
# only parentheses and bodies contain a single statement, so the only braces in the
# statement are the ones that delimit each body.
def nvoc_chain_end(text: str, start: int, what: str, filename: str) -> int:
    pos = start

    while True:
        open_brace = text.find("{", pos)
        if open_brace == -1:
            raise MyException(f"Malformed {what} in {filename}")
        # Branch bodies are never nested, so the body ends at the next '}'.
        close_brace = text.find("}", open_brace)
        if close_brace == -1:
            raise MyException(f"Malformed {what} in {filename}")
        pos = close_brace + 1
        # Skip whitespace and "// ..." comments to see if another branch follows.
        if not re.match(r"(?:\s|//[^\n]*\n)*else\b", text[pos:]):
            return pos

# Parse an NVOC-generated file and extract all of the HAL variables into a nested
# dictionary.  The outer dictionary is keyed by variable name, and each of its values is
# an inner dictionary that maps each GPU to the value the variable has there.  A variable
# that does not vary by chip has the same value recorded for every GPU in `supported`.
#
# `required` names the variables this caller goes on to read.  Those must cover every GPU
# in `supported` if the file defines them at all, because a partially covered variable
# would otherwise be read as a zero or a KeyError further down.  A generated file holds
# many variables besides the ones we want, so anything outside `required` is returned
# with whatever coverage it happens to have rather than failing the run.
def parse_nvoc_hals(filename, required) -> dict:
    if not os.path.exists(filename):
        return {}

    with open(filename) as f:
        text = f.read()

    pattern = re.compile(r"^[ \t]*//[ \t]*Hal field --[ \t]*([a-zA-Z]+)[ \t]*\n", re.MULTILINE)
    hals2 = {}

    for marker in pattern.finditer(text):
        variable = marker.group(1)

        # Fields that have the same value on every chip are assigned unconditionally, with
        # no if / else chain at all, so the value is the catch-all default.
        unconditional = re.compile(rf"\s*pThis->{variable}\s*=\s*(.*?);", re.DOTALL)
        assignment = unconditional.match(text, marker.end())
        if assignment:
            hals2[variable] = {}
            value = parse_c_value(assignment.group(1))
            for gpu in supported:
                hals2[variable][gpu] = value
            continue

        # Otherwise the field is initialized by a single if / else-if / else statement that
        # begins right after the marker.
        block = text[marker.end():nvoc_chain_end(text, marker.end(),
                                                 f"Hal field '{variable}'", filename)]

        field = {}
        # Each if / else-if branch ends its condition with a "/* ChipHal: GPU1 | GPU2 | ... */"
        # comment, immediately followed by a "{ pThis-><variable> = <value>; }" body.
        # re.DOTALL lets both the GPU list and the value span multiple lines.  The GPU list
        # is matched as chip names, separators and whitespace rather than as ".*?", so that
        # a branch whose body holds no assignment cannot be bridged over: "." would happily
        # run past the closing "*/" and swallow the following branch's first GPU.
        branch = re.compile(
            rf"/\*\s*ChipHal:\s*([\w\s|]+?)\s*\*/\s*"
            rf"\{{\s*pThis->{variable}\s*=\s*(.*?);\s*\}}",
            re.DOTALL)
        for gpus, value in branch.findall(block):
            for gpu in gpus.split("|"):
                gpu = gpu.strip().lower()
                if gpu in supported:
                    field[gpu] = parse_c_value(value)

        # The trailing "// default" / else branch is the catch-all.
        default = re.search(
            rf"//\s*default\s*else\s*\{{\s*pThis->{variable}\s*=\s*(.*?);\s*\}}",
            block, re.DOTALL)
        if default:
            value = parse_c_value(default.group(1))
            for gpu in supported:
                field.setdefault(gpu, value)

        if variable in required and len(field) != len(supported):
            raise MyException(f"Expected {len(supported)} GPUs for '{variable}' in {filename} but found {len(field)}")

        hals2[variable] = field

    return hals2

# Inline HAL bodies for each NVOC header, keyed by file name, so that a header holding
# several halified methods is only scanned once.
nvoc_inline_bodies_cache = {}

# NVOC emits the simplest HAL implementations as inline functions in the generated
# header, as in
#
#   static inline NvU32 kpmuReservedMemoryBackingStoreSizeGet_bdab1d(struct KernelPmu *pKernelPmu){
#       return 9437184;
#   }
#
# Return a dictionary mapping every such function name to its return expression.  An
# implementation that is a real function in a .c file has no entry here.
def nvoc_inline_bodies(filename: str) -> dict:
    if filename in nvoc_inline_bodies_cache:
        return nvoc_inline_bodies_cache[filename]

    with open(filename) as f:
        text = f.read()

    pattern = re.compile(
        r"static\s+inline\s+\w+\s+(\w+)\s*\([^)]*\)\s*\{\s*return\s+(.*?);\s*\}", re.DOTALL)
    bodies = dict(pattern.findall(text))

    nvoc_inline_bodies_cache[filename] = bodies
    return bodies

# A halified method is dispatched through a function pointer that NVOC assigns with the
# same if / else-if / else chain it uses for Hal fields, except that each branch body
# stores an implementation instead of a value:
#
#   // kpmuReservedMemoryBackingStoreSizeGet -- halified (3 hals) body
#   if (...) /* ChipHal: GR100 | GR102 */
#   {
#       pThis->__kpmuReservedMemoryBackingStoreSizeGet__ = &kpmuReservedMemoryBackingStoreSizeGet_3c0c39;
#   }
#
# Return a dictionary mapping every GPU in `supported` to the name of the implementation
# the method resolves to on that chip, or an empty dictionary if the method is not halified
# in this source tree.
#
# NVOC nests this chain inside an RmVariantHal test, and emits branches with no assignment
# at all ("// NVOC_UNREACHABLE, NULL-initialized.") for chips that cannot reach the method.
# Both are handled: nvoc_chain_end() walks through the nesting, and the GPU list is matched
# as chip names rather than as ".*?" so an assignment-less branch cannot be bridged over.
def parse_nvoc_hal_dispatch(c_filename: str, method: str) -> dict:
    if not os.path.exists(c_filename):
        return {}

    with open(c_filename) as f:
        text = f.read()

    marker = re.search(rf"^[ \t]*//[ \t]*{method}[ \t]*--[ \t]*halified[^\n]*\n",
                       text, re.MULTILINE)
    if not marker:
        return {}

    block = text[marker.end():nvoc_chain_end(text, marker.end(),
                                             f"HAL method '{method}'", c_filename)]

    field = {}
    branch = re.compile(
        rf"/\*\s*ChipHal:\s*([\w\s|]+?)\s*\*/\s*"
        rf"\{{\s*pThis->__{method}__\s*=\s*&(\w+);\s*\}}",
        re.DOTALL)
    for gpus, implementation in branch.findall(block):
        for gpu in gpus.split("|"):
            gpu = gpu.strip().lower()
            if gpu in supported:
                field[gpu] = implementation

    # The trailing else is the catch-all.  Unlike a Hal field, NVOC only labels it
    # "// default" when the method declares an explicit default implementation, so match
    # the else itself rather than the comment.
    default = re.search(rf"else\s*\{{\s*pThis->__{method}__\s*=\s*&(\w+);\s*\}}\s*$",
                        block.rstrip())
    if default:
        for gpu in supported:
            field.setdefault(gpu, default.group(1))

    if len(field) != len(supported):
        raise MyException(f"Expected {len(supported)} GPUs for HAL method '{method}' in "
                          f"{c_filename} but found {len(field)}")

    return field

# When every implementation is an inline constant, the dispatch is enough to recover the
# value the method returns on each chip.  Return a dictionary mapping every GPU in
# `supported` to that value, or an empty dictionary if the method is not halified here.
def parse_nvoc_hal_method(c_filename: str, h_filename: str, method: str) -> dict:
    if not os.path.exists(h_filename):
        return {}

    dispatch = parse_nvoc_hal_dispatch(c_filename, method)
    if not dispatch:
        return {}

    bodies = nvoc_inline_bodies(h_filename)

    def value_of(implementation: str) -> int | bool:
        if implementation not in bodies:
            raise MyException(f"HAL method '{method}' in {c_filename} dispatches to "
                              f"{implementation}, which is not an inline constant in {h_filename}")
        return parse_c_value(bodies[implementation])

    return {gpu: value_of(implementation) for gpu, implementation in dispatch.items()}

# Look up the value of a HAL field for one GPU.
def hal_value(field: str, gpu: str) -> int | bool:
    if field not in hals:
        raise MyException(f"HAL field '{field}' is not defined")

    values = hals[field]

    if gpu in values:
        return values[gpu]

    raise MyException(f"HAL field '{field}' has no value for {gpu} and no default")

# Write a dictionary of HAL variables to nvoc-<version>.txt as an ASCII table, one column
# per variable and one row per GPU.  Values print as hexadecimal, except for the booleans
# some NVOC fields hold, which print as True / False because 0x1 would be needlessly
# cryptic.  A variable that has no value for a GPU gets an empty cell.
def print_hals(hals2: dict):
    global outputpath
    global version

    fields = list(hals2)

    # Take the GPUs in the order they were added, which for a fully initialized table is
    # the order of `supported`.  A variable is not required to cover every GPU.
    gpus = list(dict.fromkeys(gpu for values in hals2.values() for gpu in values))

    def cell(field: str, gpu: str) -> str:
        if gpu not in hals2[field]:
            return ""
        value = hals2[field][gpu]
        return str(value) if isinstance(value, bool) else f"0x{value:X}"

    headings = ["GPU"] + fields
    rows = [[gpu] + [cell(field, gpu) for field in fields] for gpu in gpus]

    # Size every column to its widest entry, heading included.
    widths = [max(len(row[column]) for row in [headings] + rows)
              for column in range(len(headings))]

    # GPU names read better left-aligned, numbers right-aligned.
    def line(cells: list) -> str:
        padded = [cells[0].ljust(widths[0])]
        padded += [cell.rjust(width) for cell, width in zip(cells[1:], widths[1:])]
        return "| " + " | ".join(padded) + " |"

    rule = "+" + "+".join("-" * (width + 2) for width in widths) + "+"

    filename = f"nvoc-{version}.txt"
    print(f"Creating {filename}")

    with open(os.path.join(tempfile.gettempdir(), filename), "w") as f:
        print(f"GSP-RM version {version}", file = f)
        print("\n".join([rule, line(headings), rule] + [line(row) for row in rows] + [rule]),
              file = f)

# RM headers guard many of their constants with "#if" blocks that select between build
# configurations, so a header is read by running it through pcpp's C preprocessor rather
# than by pattern matching its text.  The preprocessor evaluates those conditionals the way
# a compiler does, so only the definitions from the branch that is actually taken survive.
class HeaderPreprocessor(Preprocessor):
    # Headers that are not on the search path are dropped rather than reported as errors,
    # because most of what an RM header includes is irrelevant here.  The macros such a
    # header would have defined are then simply undefined, and since an undefined name
    # evaluates to 0 in an "#if", the result is the branch that a build with the feature
    # turned off would take.
    def on_include_not_found(self, is_malformed, is_system_include, curdir, includepath):
        raise OutputDirective(Action.IgnoreAndRemove)

    # The default prints to stderr and keeps going with a bad parse.
    def on_error(self, file, line, msg):
        raise MyException(f"{file}:{line}: {msg}")

# Headers that have already been preprocessed, keyed by file name, so that the repeated
# lookups parse_legacy_hals() makes in one header only preprocess it once.
preprocessed_headers = {}

# Preprocess a header and return the Preprocessor, whose "macros" dictionary then holds
# every macro that is still defined at the end of the file.
def preprocess_header(filename: str) -> Preprocessor:
    if filename in preprocessed_headers:
        return preprocessed_headers[filename]

    pp = HeaderPreprocessor()

    # RM headers include each other relative to these two directories.  Resolving those
    # includes is what gives a conditional such as "#if RMCFG_FEATURE_GSPRM_BULLSEYE" the
    # value the driver was configured with instead of the assumed default of 0.
    pp.add_path("src/nvidia/generated")
    pp.add_path("src/nvidia/inc")

    with open(filename) as f:
        pp.parse(f.read(), filename)

    # parse() only sets up the token stream.  The directives in it are executed as the
    # stream is consumed, so it has to be drained before "macros" is complete.  The
    # preprocessed text itself is of no interest.
    while pp.token():
        pass

    preprocessed_headers[filename] = pp
    return pp

# Look up an object-like "#define <macro> <expression>" in a C header and return the
# evaluated expression.  Definitions are often annotated with a trailing comment, as in
#
#   #define GSP_FW_HEAP_PARAM_BASE_RM_SIZE_GR10X              (32 << 20)   // GR10X+
#
# and long ones are continued across lines with a trailing backslash.  The preprocessor
# strips both, so the body reaches parse_c_value() as a bare expression.
#
# A definition may also name other macros, as in
#
#   #define GSP_FW_HEAP_PARAM_MAX_SUPPORTED_CHANNELS  2048   // Support 2048 channels
#   #define GSP_FW_HEAP_PARAM_CLIENT_ALLOC_SIZE      ((48 << 10) * GSP_FW_HEAP_PARAM_MAX_SUPPORTED_CHANNELS)
#
# Those names are expanded down to a literal expression first, so lookups can be made in
# any order, and an older header that spells the same value out in full needs no special
# handling.
def macro_value(filename: str, macro: str, fallback: str = None) -> int | bool:
    pp = preprocess_header(filename)

    if macro not in pp.macros and fallback:
        macro = fallback

    if macro not in pp.macros:
        raise MyException(f"Could not find {macro} in {filename}")

    definition = pp.macros[macro]

    # Only object-like macros have a value that can stand on its own.
    if definition.arglist is not None:
        raise MyException(f"{macro} in {filename} is a function-like macro")

    # expand_macros() rewrites the tokens it is handed in place, so give it copies and
    # leave the stored definition intact for the next lookup.
    body = pp.expand_macros([copy.copy(token) for token in definition.value])

    return parse_c_value("".join(token.value for token in body))

# Return the body of a hand-written function, or None if this source tree does not have
# the function at all.  The closing brace of a top-level function is the first one in
# column zero, so the body ends at the first "\n}".
def function_body(filename: str, function: str) -> str | None:
    with open(filename) as f:
        text = f.read()

    body = re.search(rf"{function}\s*\([^)]*\)\s*\{{(.*?)\n\}}", text, re.DOTALL)

    return body.group(1) if body else None

# Bodies already located by hal_implementation_body(), so that looking up the same
# implementation for a second WPR meta field does not walk the directory again.
hal_implementation_cache = {}

# Same, for a chip-specific HAL implementation, which unlike an _IMPL function can live in
# any of the per-architecture files under an engine's source directory.
def hal_implementation_body(directory: str, implementation: str) -> str | None:
    if (directory, implementation) in hal_implementation_cache:
        return hal_implementation_cache[(directory, implementation)]

    body = None
    for filename in glob.glob(os.path.join(directory, "**", "*.c"), recursive = True):
        body = function_body(filename, implementation)
        if body is not None:
            break

    hal_implementation_cache[(directory, implementation)] = body
    return body

# Older source trees compute part of the PMU reservation in hand-written code instead of
# in a HAL, so the only place the constant appears is the body of the _IMPL function:
#
#   NvU32 kpmuReservedMemoryMiscSizeGet_IMPL(KernelPmu *pKernelPmu)
#   {
#       if (kpmuGetIsSelfInit(pKernelPmu))
#       {
#           return (4U * (1U << 10U));
#       }
#
#       return 0U;
#   }
#
# These functions all return their constant from the first return statement and zero from
# the last, so take the first one.
def first_return_value(filename: str, function: str) -> int:
    body = function_body(filename, f"{function}_IMPL")
    if body is None:
        raise MyException(f"Could not find {function}_IMPL in {filename}")

    value = re.search(r"return\s+([^;]+);", body)
    if not value:
        raise MyException(f"{function}_IMPL in {filename} has no return statement")

    return parse_c_value(value.group(1))

# Calculate gspFwHeapBaseSize for each GPU:
#
#   carveout_size + base_rm_size + round_up(client_alloc_size + per_channel_size, 1MB)
#
# carveout_size is the LIBOS2 or LIBOS3 OS size depending on which one the chip runs,
# base_rm_size is the per-chip fwHeapParamBaseSize HAL, client_alloc_size is the client
# allocation, and per_channel_size is the per-chip overhead that r620 added, multiplied by
# the number of channels the heap is sized for.  RM rounds the last two terms up to a
# megabyte together rather than one at a time, so they are summed before rounding.
def parse_gsp_fw_heap_base_size() -> dict:
    macro_file = "src/nvidia/inc/kernel/gpu/gsp/gsp_fw_heap.h"

    # Contains the fwHeapParamBaseSize and fwHeapParamPerChannelOverhead variables
    kernel_gsp_nvoc = parse_nvoc_hals("src/nvidia/generated/g_kernel_gsp_nvoc.c",
                                      ["fwHeapParamBaseSize", "fwHeapParamPerChannelOverhead"])

    # Turing and GA100 use LIBOS2, all others use LIBOS3
    GSP_FW_HEAP_PARAM_OS_SIZE_LIBOS2 = macro_value(macro_file, "GSP_FW_HEAP_PARAM_OS_SIZE_LIBOS2")
    GSP_FW_HEAP_PARAM_OS_SIZE_LIBOS3_BAREMETAL = macro_value(macro_file, "GSP_FW_HEAP_PARAM_OS_SIZE_LIBOS3_BAREMETAL")

    # In some versions of OpenRM, GSP_FW_HEAP_PARAM_CLIENT_ALLOC_SIZE references
    # GSP_FW_HEAP_PARAM_MAX_SUPPORTED_CHANNELS, which macro_value() expands for us.
    GSP_FW_HEAP_PARAM_CLIENT_ALLOC_SIZE = macro_value(macro_file, "GSP_FW_HEAP_PARAM_CLIENT_ALLOC_SIZE")

    # r620 and later declare a per-channel overhead, and spell out the channel count that
    # it is charged for.  r615 has neither, which is the same arithmetic with an overhead
    # of zero, so one expression covers every release.
    per_channel_overhead = kernel_gsp_nvoc.get("fwHeapParamPerChannelOverhead", {})
    channels = (macro_value(macro_file, "GSP_FW_HEAP_PARAM_MAX_SUPPORTED_CHANNELS")
                if per_channel_overhead else 0)

    libos2_gpus = ["tu102", "tu104", "tu106", "tu116", "tu117", "ga100"]

    gspFwHeapBaseSize = {}

    for gpu in supported:
        carveout_size = (GSP_FW_HEAP_PARAM_OS_SIZE_LIBOS2 if gpu in libos2_gpus
                         else GSP_FW_HEAP_PARAM_OS_SIZE_LIBOS3_BAREMETAL)
        base_rm_size = kernel_gsp_nvoc["fwHeapParamBaseSize"][gpu]
        per_channel_size = per_channel_overhead.get(gpu, 0) * channels

        gspFwHeapBaseSize[gpu] = carveout_size + base_rm_size + round_up_to_base(
            GSP_FW_HEAP_PARAM_CLIENT_ALLOC_SIZE + per_channel_size, 1048576)

    return gspFwHeapBaseSize

# Calculate gspFwHeapSizePerGb for each GPU.  This one does not vary by chip, so the
# single macro applies to every GPU.
def parse_gsp_fw_heap_size_per_gb() -> dict:
    macro_file = "src/nvidia/inc/kernel/gpu/gsp/gsp_fw_heap.h"

    # Older versions of OpenRM called this GSP_FW_HEAP_PARAM_SIZE_PER_GB_FB.
    GSP_FW_HEAP_PARAM_SIZE_PER_GB = macro_value(macro_file, "GSP_FW_HEAP_PARAM_SIZE_PER_GB", "GSP_FW_HEAP_PARAM_SIZE_PER_GB_FB")

    gspFwHeapSizePerGb = {}

    for gpu in supported:
        gspFwHeapSizePerGb[gpu] = GSP_FW_HEAP_PARAM_SIZE_PER_GB

    return gspFwHeapSizePerGb

# Calculate gspFwHeapBaseSizeVgpu for each GPU.  OpenRM sizes the vGPU heap by how many
# VMs the chip supports, so gb202 takes the 48-VM value and gr10x the 7-VM value.  Older
# versions define only GSP_FW_HEAP_SIZE_VGPU_DEFAULT, which then stands in for both.
def parse_gsp_fw_heap_base_size_vgpu() -> dict:
    macro_file = "src/nvidia/inc/kernel/gpu/gsp/gsp_fw_heap.h"

    GSP_FW_HEAP_SIZE_VGPU_DEFAULT = macro_value(macro_file, "GSP_FW_HEAP_SIZE_VGPU_DEFAULT")

    # Older versions of OpenRM only defined GSP_FW_HEAP_SIZE_VGPU_DEFAULT
    GSP_FW_HEAP_SIZE_VGPU_7VMS = macro_value(macro_file, "GSP_FW_HEAP_SIZE_VGPU_7VMS", "GSP_FW_HEAP_SIZE_VGPU_DEFAULT")
    GSP_FW_HEAP_SIZE_VGPU_48VMS = macro_value(macro_file, "GSP_FW_HEAP_SIZE_VGPU_48VMS", "GSP_FW_HEAP_SIZE_VGPU_DEFAULT")

    # Simple sanity check
    if GSP_FW_HEAP_SIZE_VGPU_48VMS < GSP_FW_HEAP_SIZE_VGPU_7VMS:
        raise MyException(f"Invalid values for {GSP_FW_HEAP_SIZE_VGPU_7VMS=} and {GSP_FW_HEAP_SIZE_VGPU_48VMS=}")

    gspFwHeapBaseSizeVgpu = {}

    for gpu in supported:
        if gpu == "gb202":
            gspFwHeapBaseSizeVgpu[gpu] = GSP_FW_HEAP_SIZE_VGPU_48VMS
        elif gpu.startswith("gr"):
            gspFwHeapBaseSizeVgpu[gpu] = GSP_FW_HEAP_SIZE_VGPU_7VMS
        else:
            # Unlike OpenRM, Nova only supports vGPU on Blackwell and later, so
            # pre-Blackwell will never actually use gspFwHeapBaseSizeVgpu or
            # gspFwHeapSizePerVm.
            gspFwHeapBaseSizeVgpu[gpu] = GSP_FW_HEAP_SIZE_VGPU_DEFAULT

    return gspFwHeapBaseSizeVgpu

# Calculate gspFwHeapSizePerVm for each GPU.  This is zero everywhere for now, because the
# per-VM cost is still bundled into gspFwHeapBaseSizeVgpu; a future version of OpenRM will
# reduce that base and set this one properly.  Returning an empty dictionary leaves the
# zero-filling to parse_legacy_hals().
def parse_gsp_fw_heap_size_per_vm() -> dict:
    return {}

# kgspPopulateWprMeta_GH100() works out the WPR layout, but a chip whose HAL is layered on
# top of that one can overwrite individual fields afterwards.  The iGPUs do exactly that:
#
#   // Layout is close to GH100, so use that HAL first then override as necessary
#   NV_ASSERT_OK_OR_RETURN(kgspPopulateWprMeta_GH100(pGpu, pKernelGsp, pGspFw));
#   ...
#   pWprMeta->pmuReservedSize = 0; // No PMU Reserved memory in GB10B
#   ...
#   pWprMeta->nonWprHeapSize = 0;
#
# so whatever RM computed for those fields never reaches the WPR meta on an iGPU.  Zero the
# GPUs whose implementation assigns 0 to 'field', which is the WPR meta member that the
# values being passed in feed.  Matching on the assignment rather than on the name of the
# implementation picks up any future chip that does the same thing.
def apply_wpr_meta_override(field: str, values: dict) -> dict:
    dispatch = parse_nvoc_hal_dispatch("src/nvidia/generated/g_kernel_gsp_nvoc.c",
                                       "kgspPopulateWprMeta")

    zeroed = {}
    for implementation in set(dispatch.values()):
        body = hal_implementation_body("src/nvidia/src/kernel/gpu/gsp", implementation)
        zeroed[implementation] = bool(
            body and re.search(rf"pWprMeta->{field}\s*=\s*0\s*;", body))

    return {gpu: 0 if zeroed.get(dispatch.get(gpu)) else value
            for gpu, value in values.items()}

# Calculate what kpmuReservedMemorySizeGet() returns for each GPU.  The value is never
# spelled out in the source, so it has to be rebuilt from the terms RM sums, and those
# terms have been rearranged twice:
#
#   r570: ALIGN_UP(backing store + surfaces + misc), where the surfaces size
#         is one PMU_RESERVED_MEMORY_SURFACES_SIZE macro for every chip.
#   r615: the same sum, but the surfaces size became a per-chip HAL.
#   r620: ALIGN_UP(backing store), which is itself now a per-chip HAL, with
#         surfaces and misc moved out to the non-WPR carveout that
#         gpuGetPmuReservedMemoryNonWprSize() sizes.
#
# In both of the older shapes every term is zero unless the chip reports itself as "self
# init", and the backing store and misc sizes are literals in hand-written code.
def parse_pmu_reserved_size() -> dict:
    kern_pmu_c = "src/nvidia/generated/g_kern_pmu_nvoc.c"
    kern_pmu_h = "src/nvidia/generated/g_kern_pmu_nvoc.h"
    kern_pmu = "src/nvidia/src/kernel/gpu/pmu/kern_pmu.c"

    if not os.path.exists(kern_pmu_h):
        raise MyException(f"Could not find {kern_pmu_h}")

    alignment = macro_value(kern_pmu_h, "KPMU_RESERVED_MEMORY_ALIGNMENT")

    # r620 and later.  Everything needed is in the generated files.
    backing = parse_nvoc_hal_method(kern_pmu_c, kern_pmu_h,
                                    "kpmuReservedMemoryBackingStoreSizeGet")
    if backing:
        pmuReservedSize = {gpu: round_up_to_base(backing[gpu], alignment)
                           for gpu in supported}
        return apply_wpr_meta_override("pmuReservedSize", pmuReservedSize)

    self_init = parse_nvoc_hal_method(kern_pmu_c, kern_pmu_h, "kpmuGetIsSelfInit")
    if not self_init:
        raise MyException(f"Neither kpmuReservedMemoryBackingStoreSizeGet nor "
                          f"kpmuGetIsSelfInit is halified in {kern_pmu_c}")

    backing_size = first_return_value(kern_pmu, "kpmuReservedMemoryBackingStoreSizeGet")
    misc_size = first_return_value(kern_pmu, "kpmuReservedMemoryMiscSizeGet")

    surfaces = parse_nvoc_hal_method("src/nvidia/generated/g_gpu_nvoc.c",
                                     "src/nvidia/generated/g_gpu_nvoc.h",
                                     "gpuGetPmuReservedMemorySurfacesSize")
    if not surfaces:
        surfaces_size = macro_value(kern_pmu_h, "PMU_RESERVED_MEMORY_SURFACES_SIZE")
        surfaces = {gpu: surfaces_size for gpu in supported}

    pmuReservedSize = {gpu: round_up_to_base(backing_size + surfaces[gpu] + misc_size,
                                             alignment) if self_init[gpu] else 0
                       for gpu in supported}

    return apply_wpr_meta_override("pmuReservedSize", pmuReservedSize)

# Calculate what gpuGetPmuReservedMemoryNonWprSize() returns for each GPU.  r620 moved the
# surfaces and misc terms out of the WPR reservation that kpmuReservedMemorySizeGet()
# reports and into the non-WPR GSP carveout, where they are summed with no alignment of
# their own:
#
#   NvU32 gpuGetPmuReservedMemoryNonWprSize_IMPL(OBJGPU *pGpu)
#   {
#       return (gpuGetPmuReservedMemorySurfacesSize(pGpu) +
#               gpuGetPmuReservedMemoryMiscSize(pGpu));
#   }
#
# Older trees make no such split -- the whole reservation lives inside WPR -- so every GPU
# is zero on them.
#
# Nova adds this to the GSP's own portion to size the carveout, the same way RM does in
# kgspGetNonWprHeapSize(), and that sum is what lands in the WPR meta as nonWprHeapSize.
# So the iGPUs, which zero nonWprHeapSize outright, contribute nothing here either.
def parse_pmu_non_wpr_reserved_size() -> dict:
    gpu_c = "src/nvidia/generated/g_gpu_nvoc.c"
    gpu_h = "src/nvidia/generated/g_gpu_nvoc.h"
    gpu_source = "src/nvidia/src/kernel/gpu/gpu.c"

    body = function_body(gpu_source, "gpuGetPmuReservedMemoryNonWprSize_IMPL")
    if body is None:
        return {gpu: 0 for gpu in supported}

    # Both terms are per-chip HALs.  Anything else in the sum is a term this code does
    # not know how to evaluate, so refuse to guess.
    terms = set(re.findall(r"(gpu\w+)\s*\(pGpu\)", body))
    expected = {"gpuGetPmuReservedMemorySurfacesSize", "gpuGetPmuReservedMemoryMiscSize"}
    if terms != expected:
        raise MyException(f"gpuGetPmuReservedMemoryNonWprSize_IMPL in {gpu_source} sums "
                          f"{sorted(terms)}, expected {sorted(expected)}")

    surfaces = parse_nvoc_hal_method(gpu_c, gpu_h, "gpuGetPmuReservedMemorySurfacesSize")
    misc = parse_nvoc_hal_method(gpu_c, gpu_h, "gpuGetPmuReservedMemoryMiscSize")
    if not surfaces or not misc:
        raise MyException(f"gpuGetPmuReservedMemoryNonWprSize_IMPL exists in {gpu_source} "
                          f"but its terms are not halified in {gpu_c}")

    pmuNonWprReservedSize = {gpu: surfaces[gpu] + misc[gpu] for gpu in supported}

    return apply_wpr_meta_override("nonWprHeapSize", pmuNonWprReservedSize)

# Build the HAL table for a source tree whose g_gpu_arch_nvoc.c does not carry these
# values, which is still the case for every release through r620.  Each variable is
# reconstructed by its own function, from whatever gsp_fw_heap.h, the NVOC-generated files
# and the hand-written sources happen to spell out in that particular release.  A function
# that returns a partial dictionary has its remaining GPUs zero-filled here.
def parse_legacy_hals():
    hals2 = {
        "gspFwHeapBaseSize": parse_gsp_fw_heap_base_size(),
        "gspFwHeapSizePerGb": parse_gsp_fw_heap_size_per_gb(),
        "gspFwHeapBaseSizeVgpu": parse_gsp_fw_heap_base_size_vgpu(),
        "gspFwHeapSizePerVm": parse_gsp_fw_heap_size_per_vm(),
        "pmuReservedSize": parse_pmu_reserved_size(),
        "pmuNonWprReservedSize": parse_pmu_non_wpr_reserved_size(),
    }

    for hal in hals2:
        for gpu in supported:
            hals2[hal].setdefault(gpu, 0)

    return hals2

# Perform a deep merge of a partial HAL dictionary into the global variable hals{}.
# GPUs that are not in `supported` are dropped.
def update_hals(update: dict):
    global hals

    for field, values in update.items():
        hals.setdefault(field, {}).update(
            {gpu: value for gpu, value in values.items() if gpu in supported})

# -------------------------------------------------------------------
# Generate firmware binaries
# -------------------------------------------------------------------

# Generic Falcon bootloader.  First, FWSEC runs on the RISC-V GSP core.
# Then this generic bootloader runs on the SEC2 core, in order to restart the GSP
# core to run GSP-RM on it.  This is only used on TU10x and GA100 GPUs.
def generic_bootloader(gpu):
    GPU = gpu.upper()
    filename = f"src/nvidia/generated/g_bindata_ksec2GetBinArchiveBlUcode_{GPU}.c"

    tlv = TLV("gen_bootloader", gpu)

    # Extract the descriptor (RM_FLCN_BL_DESC)
    descriptor = get_bytes(filename, f"RM_FLCN_BL_DESC ksec2BinArchiveBlUcode_{GPU}", "ucode_desc")
    (start_tag, dmem_load_off, code_offset, code_size, data_off,
        data_size) = struct.unpack("<6I", descriptor)
    # Both RM and Nova only load the code section, and both assume that
    # code_off and dmem_load_off are zero.
    if code_offset != 0:
        raise MyException(f"code offset in ksec2BinArchiveBlUcode_{GPU} should be 0 but is {code_offset}")
    if dmem_load_off != 0:
        raise MyException(f"dmem load offset in ksec2BinArchiveBlUcode_{GPU} should be 0 but is {dmem_load_off}")
    # Ensure the start tag fits in the register
    if start_tag > 65535:
        raise MyException(f"start tag in ksec2BinArchiveBlUcode_{GPU} value of {start_tag} is too large")

    # Extract the actual bootloader firmware
    firmware = get_bytes(filename, f"ksec2BinArchiveBlUcode_{GPU}", "ucode_image")
    if code_offset + code_size > len(firmware):
        raise MyException(f"{code_offset=} + {code_size=} in ksec2BinArchiveBlUcode_{GPU} exceeds image size of {len(firmware)}")

    tlv.add("STRT", start_tag)
    tlv.add("CDSZ", code_size)

    tlv.add("BLOB", firmware)

    tlv.write()

# GSP bootloader
def gsp_bootloader(gpu: str, debug = None):
    if debug is not None:
        fuse = "_dbg" if debug else "_prod"
        name = f"gsp-bootloader-{gpu}-{'dbg' if debug else 'prod'}"
    else:
        fuse = ""
        name = f"gsp-bootloader-{gpu}"

    GPU = gpu.upper()
    filename = f"src/nvidia/generated/g_bindata_kgspGetBinArchiveGspRmBoot_{GPU}.c"

    tlv = TLV("gsp_bootloader", gpu)

    # Extract the descriptor (RM_RISCV_UCODE_DESC)
    # Note: the size of RM_RISCV_UCODE_DESC varies from version to version, but Nova
    # only cares about the first few fields.  So we use unpack_from() which ignores excess
    # bytes.
    descriptor = get_bytes(filename, f"kgspBinArchiveGspRmBoot_{GPU}", f"ucode_desc{fuse}")
    (desc_version, bootloader_offset, bootloader_size, bootloader_param_offset, bootloader_param_size,
     riscv_elf_offset, riscv_elf_size, app_version, manifest_offset, manifest_size, monitor_data_offset,
     monitor_data_size, monitor_code_offset, monitor_code_size) = struct.unpack_from("<14I", descriptor)

    if desc_version < 4:
        raise MyException(f"unsupported version {desc_version} for {name}")

    # Extract the actual bootloader firmware
    firmware = get_bytes(filename, f"kgspBinArchiveGspRmBoot_{GPU}", f"ucode_image{fuse}")

    # Validate a few of the offsets
    if manifest_offset + manifest_size > len(firmware):
        raise MyException(f"{manifest_offset=} + {manifest_size=} is too large for {name} (size={len(firmware)})")
    if monitor_data_offset + monitor_data_size > len(firmware):
        raise MyException(f"{monitor_data_offset=} + {monitor_data_size=} is too large for {name} (size={len(firmware)})")
    if monitor_code_offset + monitor_code_size > len(firmware):
        raise MyException(f"{monitor_code_offset=} + {monitor_code_size=} is too large for {name} (size={len(firmware)})")

    if manifest_offset % 256 != 0:
        raise MyException(f"{manifest_offset=} is not 256-byte aligned")
    if monitor_data_offset % 256 != 0:
        raise MyException(f"{monitor_data_offset=} is not 256-byte aligned")
    if monitor_code_offset % 256 != 0:
        raise MyException(f"{monitor_code_offset=} is not 256-byte aligned")

    tlv.add("CDOF", monitor_code_offset)
    tlv.add("DAOF", monitor_data_offset)
    tlv.add("MFOF", manifest_offset)
    tlv.add("APPV", app_version)

    tlv.add("BLOB", firmware)
    tlv.write()

# GSP Booter load and unload
def booter(gpu, load, sigsize, debug = False):
    fuse = "dbg" if debug else "prod"
    GPU = gpu.upper()
    LOAD = load.capitalize()
    name = f"booter-{load}-{gpu}-{fuse}"

    filename = f"src/nvidia/generated/g_bindata_kgspGetBinArchiveBooter{LOAD}Ucode_{GPU}.c"

    tlv = TLV(f"booter_{load}", gpu)

    # Query the number of signatures.  This should be a 4-byte array (32-bit little-endian integer)
    raw = get_bytes(filename, f"kgspBinArchiveBooter{LOAD}Ucode_{GPU}", "num_sigs")
    if len(raw) != 4:
        raise MyException(f"num_sigs array for {name} is wrong size of {len(raw)}")
    num_sigs = struct.unpack("<I", raw)[0]
    if num_sigs < 1 or num_sigs > 15:
        raise MyException(f"out of range number of signatures ({num_sigs}) for {name}")
    tlv.add("NSIG", num_sigs)

    # Extract the signatures.  Technically, we don't need to pass the signature size to
    # this function, but doing so allows us to double-check all the array sizes.
    signatures = get_bytes(filename, f"kgspBinArchiveBooter{LOAD}Ucode_{GPU}", f"sig_{fuse}")
    signatures_size = len(signatures)
    if signatures_size % sigsize:
        raise MyException(f"signature file size for {name} is {signatures_size}, an uneven multiple of {sigsize}")
    if num_sigs != signatures_size // sigsize:
        raise MyException(f"mismatch number of signatures ({signatures_size // sigsize}), should be {num_sigs}")
    tlv.add("SIGN", signatures)

    # Extract the patch location
    raw = get_bytes(filename, f"kgspBinArchiveBooter{LOAD}Ucode_{GPU}", "patch_loc")
    if len(raw) != 4:
        raise MyException(f"patch_loc[] array for {name} should be one element, but is {len(raw)} bytes.")
    patchloc = struct.unpack("<I", raw)[0]
    tlv.add("PLOC", patchloc)

    # Extract the patch sig offset.  RM expects this to be zero, but doesn't use it,
    # so if it's ever non-zero, something has changed.
    raw = get_bytes(filename, f"kgspBinArchiveBooter{LOAD}Ucode_{GPU}", "patch_sig")
    if len(raw) != 4:
        raise MyException(f"patch_sig[] array for {name} should be one element, but is {len(raw)} bytes.")
    patchsig = struct.unpack("<I", raw)[0]
    if patchsig != 0:
        raise MyException(f"patch_sig for {name} should be 0, but is instead {patchsig}.")

    # Extract the patch meta variables
    raw = get_bytes(filename, f"kgspBinArchiveBooter{LOAD}Ucode_{GPU}", "patch_meta")
    fuse_ver, engine_id, ucode_id = struct.unpack("<III", raw)
    tlv.add("FUSE", fuse_ver)
    tlv.add("ENID", engine_id)
    tlv.add("UCID", ucode_id)

    # Extract the descriptor (nvfw_hs_load_header_v2)
    descriptor = get_bytes(filename, f"kgspBinArchiveBooter{LOAD}Ucode_{GPU}", f"header_{fuse}")
    if len(descriptor) < 36:
        raise MyException(f"nvfw_hs_load_header_v2 descriptor for {name} must be at least 36 bytes, but is instead {len(descriptor)} bytes.")

    # Extract some of individual fields of nvfw_hs_load_header_v2
    (os_code_offset, os_code_size, os_data_offset, os_data_size, num_apps,
     app_code_offset, app_code_size, app_data_offset, app_data_size) = struct.unpack_from("<9I", descriptor)
    # Verify that sizeof(descriptor) == 5 * 4 + num_apps * 16
    if len(descriptor) != 5 * 4 + num_apps * 16:
        raise MyException(f"nvfw_hs_load_header_v2 descriptor for {name} should be {5 * 4 + num_apps * 16} bytes, but is instead {len(descriptor)} bytes.")
    # Nova depends on os_code_size == app_code_offset
    if os_code_size != app_code_offset:
        raise MyException(f"nvfw_hs_load_header_v2 descriptor for {name} has os_code_size={os_code_size} and app_code_offset={app_code_offset}, but they should be the same.")

    # Extract the actual booter firmware
    firmware = get_bytes(filename, f"kgspBinArchiveBooter{LOAD}Ucode_{GPU}", f"image_{fuse}")

    if os_code_size + os_data_size + app_code_size > len(firmware):
        raise MyException(f"{os_code_size=} + {os_data_size=} + {app_code_size=} for {name} exceeds image size of {len(firmware)}")
    if os_code_offset + os_code_size > len(firmware):
        raise MyException(f"{os_code_offset=} + {os_code_size=} for {name} exceeds image size of {len(firmware)}")
    if os_data_offset + os_data_size > len(firmware):
        raise MyException(f"{os_data_offset=} + {os_data_size=} for {name} exceeds image size of {len(firmware)}")
    if app_code_offset + app_code_size > len(firmware):
        raise MyException(f"{app_code_offset=} + {app_code_size=} for {name} exceeds image size of {len(firmware)}")

    tlv.add("CDOF", os_code_offset)
    tlv.add("CDSZ", os_code_size)
    tlv.add("DAOF", os_data_offset)
    tlv.add("DASZ", os_data_size)
    tlv.add("A0CO", app_code_offset)
    tlv.add("A0CS", app_code_size)

    tlv.add("BLOB", firmware)

    tlv.write()

# GPU memory scrubber, needed for some GPUs and configurations
def scrubber(gpu, sigsize, debug = False):
    fuse = "dbg" if debug else "prod"
    # Unfortunately, RM breaks convention with the scrubber image and labels
    # the files and arrays with AD10X instead of AD102.
    GPUX = f"{gpu[:-1].upper()}X"
    name = f"scrubber-{gpu}-{fuse}"

    filename = f"src/nvidia/generated/g_bindata_ksec2GetBinArchiveSecurescrubUcode_{GPUX}.c"

    tlv = TLV("scrubber", gpu)

    # Query the number of signatures.  This should be a 4-byte array (32-bit little-endian integer)
    raw = get_bytes(filename, f"ksec2BinArchiveSecurescrubUcode_{GPUX}", "num_sigs")
    if len(raw) != 4:
        raise MyException(f"num_sigs array for {name} is wrong size of {len(raw)}")
    num_sigs = struct.unpack("<I", raw)[0]
    if num_sigs < 1 or num_sigs > 15:
        raise MyException(f"out of range number of signatures ({num_sigs}) for {name}")
    tlv.add("NSIG", num_sigs)

    # Extract the signatures.  Technically, we don't need to pass the signature size to
    # this function, but doing so allows us to double-check all the array sizes.
    signatures = get_bytes(filename, f"ksec2BinArchiveSecurescrubUcode_{GPUX}", f"sig_{fuse}")
    signatures_size = len(signatures)
    if signatures_size % sigsize:
        raise MyException(f"signature file size for {name} is {signatures_size}, an uneven multiple of {sigsize}")
    if num_sigs != signatures_size // sigsize:
        raise MyException(f"mismatch number of signatures ({signatures_size // sigsize}), should be {num_sigs}")
    tlv.add("SIGN", signatures)

    # Extract the patch location
    raw = get_bytes(filename, f"ksec2BinArchiveSecurescrubUcode_{GPUX}", "patch_loc")
    if len(raw) != 4:
        raise MyException(f"patch_loc[] array for {name} should be one element, but is {len(raw)} bytes.")
    patchloc = struct.unpack("<I", raw)[0]
    tlv.add("PLOC", patchloc)

    # Extract the patch sig offset.  RM expects this to be zero, but doesn't use it,
    # so if it's ever non-zero, something has changed.
    raw = get_bytes(filename, f"ksec2BinArchiveSecurescrubUcode_{GPUX}", "patch_sig")
    if len(raw) != 4:
        raise MyException(f"patch_sig[] array for {name} should be one element, but is {len(raw)} bytes.")
    patchsig = struct.unpack("<I", raw)[0]
    if patchsig != 0:
        raise MyException(f"patch_sig for {name} should be 0, but is instead {patchsig}.")

    # Extract the patch meta variables
    raw = get_bytes(filename, f"ksec2BinArchiveSecurescrubUcode_{GPUX}", "patch_meta")
    fuse_ver, engine_id, ucode_id = struct.unpack("<III", raw)
    tlv.add("FUSE", fuse_ver)
    tlv.add("ENID", engine_id)
    tlv.add("UCID", ucode_id)

    # Extract the descriptor (nvfw_hs_load_header_v2)
    descriptor = get_bytes(filename, f"ksec2BinArchiveSecurescrubUcode_{GPUX}", f"header_{fuse}")
    if len(descriptor) < 36:
        raise MyException(f"nvfw_hs_load_header_v2 descriptor for {name} must be at least 36 bytes, but is instead {len(descriptor)} bytes.")

    # Extract some of individual fields of nvfw_hs_load_header_v2
    (os_code_offset, os_code_size, os_data_offset, os_data_size, num_apps,
     app_code_offset, app_code_size, app_data_offset, app_data_size) = struct.unpack_from("<9I", descriptor)
    # Verify that sizeof(descriptor) == 5 * 4 + num_apps * 16
    if len(descriptor) != 5 * 4 + num_apps * 16:
        raise MyException(f"nvfw_hs_load_header_v2 descriptor for {name} should be {5 * 4 + num_apps * 16} bytes, but is instead {len(descriptor)} bytes.")
    # Nova depends on os_code_size == app_code_offset
    if os_code_size != app_code_offset:
        raise MyException(f"nvfw_hs_load_header_v2 descriptor for {name} has os_code_size={os_code_size} and app_code_offset={app_code_offset}, but they should be the same.")

    # Extract the actual scrubber firmware
    firmware = get_bytes(filename, f"ksec2BinArchiveSecurescrubUcode_{GPUX}", f"image_{fuse}")

    if os_code_size + os_data_size + app_code_size > len(firmware):
        raise MyException(f"{os_code_size=} + {os_data_size=} + {app_code_size=} for {name} exceeds image size of {len(firmware)}")
    if os_code_offset + os_code_size > len(firmware):
        raise MyException(f"{os_code_offset=} + {os_code_size=} for {name} exceeds image size of {len(firmware)}")
    if os_data_offset + os_data_size > len(firmware):
        raise MyException(f"{os_data_offset=} + {os_data_size=} for {name} exceeds image size of {len(firmware)}")
    if app_code_offset + app_code_size > len(firmware):
        raise MyException(f"{app_code_offset=} + {app_code_size=} for {name} exceeds image size of {len(firmware)}")

    tlv.add("CDOF", os_code_offset)
    tlv.add("CDSZ", os_code_size)
    tlv.add("DAOF", os_data_offset)
    tlv.add("DASZ", os_data_size)
    tlv.add("A0CO", app_code_offset)
    tlv.add("A0CS", app_code_size)

    tlv.add("BLOB", firmware)

    tlv.write()

# Firmware Management Controller, replaces booter to load GSP-RM.
def fmc(gpu: str, debug = False):
    fuse = "Debug" if debug else "Prod"
    GPU = gpu.upper()
    filename = f"src/nvidia/generated/g_bindata_kgspGetBinArchiveGspRmFmcGfw{fuse}Signed_{GPU}.c"

    tlv = TLV("fmc", gpu)

    ucode_hash = get_bytes(filename, f"kgspBinArchiveGspRmFmcGfw{fuse}Signed_{GPU}", "ucode_hash")
    if len(ucode_hash) != 48:
        raise MyException(f"FSP hash length for {gpu} should be 48 but is {len(ucode_hash)}")
    tlv.add("HASH", ucode_hash)

    # Some GPUs use RSAPSS3K (384-byte sig/pkey), and others use ECDSAP384
    # (97/97-byte sig).  Just make some simple range checks that Nova expects.

    ucode_sig = get_bytes(filename, f"kgspBinArchiveGspRmFmcGfw{fuse}Signed_{GPU}", "ucode_sig")
    if len(ucode_sig) < 96 or len(ucode_sig) > 384:
        raise MyException(f"FSP signature for {gpu} has an invalid length of {len(ucode_sig)}")
    tlv.add("SIGN", ucode_sig)

    ucode_pkey = get_bytes(filename, f"kgspBinArchiveGspRmFmcGfw{fuse}Signed_{GPU}", "ucode_pkey")
    if len(ucode_pkey) < 97 or len(ucode_pkey) > 384:
        raise MyException(f"FSP public key for {gpu} has an invalid length of {len(ucode_pkey)}")
    tlv.add("PKEY", ucode_pkey)

    ucode_image = get_bytes(filename, f"kgspBinArchiveGspRmFmcGfw{fuse}Signed_{GPU}", "ucode_image")
    tlv.add("BLOB", ucode_image)

    tlv.write()

def fwimage_from_gsp_elf(filename: str, gpu: str):
    global outputpath

    elf = ELF64(filename)

    os.makedirs(os.path.join(outputpath, "nvidia", nvidiadir, gpu, subdir), exist_ok = True)

    with open(os.path.join(outputpath, "nvidia", nvidiadir, gpu, subdir, "gsp.bin"), "wb") as f:
        f.write(elf.section(".fwimage"))

    print(f"Created {os.path.join(gpu, subdir, 'gsp.bin')} from {filename}")

# Generate a gsp.tlv file that points to the correct GSP image.
# `elf` is the original ELF image from the .run file or build.
# `signame` is the name of the .fwsignature section to extract.
# `gpu` is the GPU name.
def gsp_tlv_from_elf(elf: ELF64, signame: str, gpu: str):
    signature = elf.section(signame)

    tlv = TLV("gsp", gpu)
    tlv.add("SIGN", signature)
    tlv.add("SIZE", len(elf.section(".fwimage")))
    tlv.add("FILE", "gsp.bin")

    # Also pick up the HAL variables
    for tag, field in hal_tlv_tags.items():
        tlv.add(tag, hal_value(field, gpu))

    # The ".note.gnu.build-id" section contains a 16-byte ELF note header
    # followed by the 20-byte build ID.
    build_id = elf.section(".note.gnu.build-id")
    tlv.add("BLID", build_id[16:])

    tlv.write()

# Copy ucodes binaries if present (r610+) and creates its TLV.  Each ucodes.bin
# is paired with the corresponding gsp.bin and loaded separately by the driver.
def ucodes(gsp_source):
    global outputpath

    tu10x_ucodes_src = os.path.join(gsp_source, "ucodes_tu10x.bin")
    ga10x_ucodes_src = os.path.join(gsp_source, "ucodes_ga10x.bin")

    if os.path.exists(tu10x_ucodes_src):
        tlv = TLV("ucodes", "tu102")
        tlv.add("SIZE", os.path.getsize(tu10x_ucodes_src))
        tlv.add("FILE", "ucodes.bin")
        tlv.write()

        os.makedirs(os.path.join(outputpath, "nvidia", nvidiadir, "tu102", subdir), exist_ok = True)
        shutil.copyfile(tu10x_ucodes_src,
                        os.path.join(outputpath, "nvidia", nvidiadir, "tu102", subdir, "ucodes.bin"))
        print(f"Copied ucodes_tu10x.bin to {os.path.join('nvidia', nvidiadir, 'tu102', subdir, 'ucodes.bin')}")

    if os.path.exists(ga10x_ucodes_src):
        tlv = TLV("ucodes", "ga102")
        tlv.add("SIZE", os.path.getsize(ga10x_ucodes_src))
        tlv.add("FILE", "ucodes.bin")
        tlv.write()

        os.makedirs(os.path.join(outputpath, "nvidia", nvidiadir, "ga102", subdir), exist_ok = True)
        shutil.copyfile(ga10x_ucodes_src,
                        os.path.join(outputpath, "nvidia", nvidiadir, "ga102", subdir, "ucodes.bin"))
        print(f"Copied ucodes_ga10x.bin to {os.path.join('nvidia', nvidiadir, 'ga102', subdir, 'ucodes.bin')}")

# Extract the GSP-RM binaries and create the TLV files for each GPU that has its own
# .fwsignature section.
def gsprm(tu10x_gsp_src, ga10x_gsp_src):
    global outputpath

    fwimage_from_gsp_elf(tu10x_gsp_src, "tu102")
    fwimage_from_gsp_elf(ga10x_gsp_src, "ga102")

    elf = ELF64(tu10x_gsp_src)
    gsp_tlv_from_elf(elf, ".fwsignature_tu10x", "tu102")
    gsp_tlv_from_elf(elf, ".fwsignature_tu11x", "tu116")
    gsp_tlv_from_elf(elf, ".fwsignature_ga100", "ga100")

    elf = ELF64(ga10x_gsp_src)
    gsp_tlv_from_elf(elf, ".fwsignature_ga10x", "ga102")
    gsp_tlv_from_elf(elf, ".fwsignature_ad10x", "ad102")
    gsp_tlv_from_elf(elf, ".fwsignature_gh100", "gh100")
    gsp_tlv_from_elf(elf, ".fwsignature_gb10x", "gb100")
    gsp_tlv_from_elf(elf, ".fwsignature_gb20x", "gb202")

    # GB20x is unique in that gsp.tlv has some differences
    # among the GPU variants, so we need to create unique
    # files for all of them.
    for gpu in ["gb203", "gb205", "gb206", "gb207"]:
        gsp_tlv_from_elf(elf, ".fwsignature_gb20x", gpu)

    if "gb10b" in supported:
        gsp_tlv_from_elf(elf, ".fwsignature_gb10y", "gb10b")
    if "gb20b" in supported:
        gsp_tlv_from_elf(elf, ".fwsignature_gb20y", "gb20b")
    if "gr100" in supported:
        gsp_tlv_from_elf(elf, ".fwsignature_gr10x", "gr100")

# Extract the GSP-RM firmware from the .run file and copy the binaries
# to the target directory.
def gsp_firmware_from_run(filename):
    with tempfile.TemporaryDirectory() as temp:
        directory = extract_run_file(filename, temp)

        tu10x_gsp_src = os.path.join(directory, "gsp_tu10x.bin")
        ga10x_gsp_src = os.path.join(directory, "gsp_ga10x.bin")

        gsprm(tu10x_gsp_src, ga10x_gsp_src)
        ucodes(directory)

# Extract GSP firmware from a local build output directory.
# This is an NVIDIA-internal feature for use with internal build systems.
def gsp_firmware_from_build(gsp_build_dir):
    if not os.path.isdir(gsp_build_dir):
        raise MyException(f"GSP build directory does not exist: {gsp_build_dir}")

    tu10x_gsp_src = os.path.join(gsp_build_dir, "gsp_tu10x.bin")
    ga10x_gsp_src = os.path.join(gsp_build_dir, "gsp_ga10x.bin")

    if not os.path.exists(tu10x_gsp_src) or not os.path.exists(ga10x_gsp_src):
        raise MyException(f"Firmware files are missing in {gsp_build_dir}")

    gsprm(tu10x_gsp_src, ga10x_gsp_src)
    ucodes(gsp_build_dir)

# Find the .run file and extract the GSP-RM binaries from it.
#
# `pathspec` is either
# 1) empty string -- determine the URL to download the .run file that matches the current OpenRM tree
# 2) url -- download the .run file from that URL
# 3) filename -- use the specific filename
# 4) path -- extract the binaries from the local build
def driver(pathspec):
    global version

    if pathspec == "":
        # No path/url provided, so make a guess of the URL
        # to automatically download the right version.
        pathspec = f"https://download.nvidia.com/XFree86/Linux-x86_64/{version}/NVIDIA-Linux-x86_64-{version}.run"

    if re.search("^https?://", pathspec):
        with tempfile.NamedTemporaryFile(prefix = f"NVIDIA-Linux-x86_64-{version}-", suffix = ".run") as f:
            print(f"Downloading driver from {pathspec} as {f.name}")
            try:
                urllib.request.urlretrieve(pathspec, f.name)
            except urllib.error.HTTPError as e:
                if e.code == 404:
                    raise MyException(f"Driver version {version} not found at download.nvidia.com.")
                raise MyException(f"Failed to download {pathspec}: HTTP {e.code} {e.reason}")
            except urllib.error.URLError as e:
                raise MyException(f"Failed to download {pathspec}: {e.reason}")

            gsp_firmware_from_run(f.name)
    elif os.path.isfile(pathspec) and os.access(pathspec, os.R_OK):
        gsp_firmware_from_run(pathspec)
    elif os.path.isdir(pathspec):
        gsp_firmware_from_build(pathspec)
    else:
        raise MyException(f"{pathspec} does not exist or is unreadable.")

# Two kinds of symlinks are created by the script: a symlink from one firmware file
# for one GPU to the matching file for another GPU, or a symlink from the directory
# of one GPU variant to its primary (e.g. GB203 -> GB202).
# This function standardizes the process of making those links.

# When linking one GPU to another, Nouveau compatibility must be considered.  For
# Turing and Ampere, Nouveau created multiple subdirectories for each GPU that
# includes non-GSP firmware files.  These other directories must not be touched.
def link_gpu(dest_gpu: str, src_gpu: str, filename: str | None = None):
    global outputpath
    global nvidiadir
    global subdir

    if filename:
        # We only support linking files to the same filename in another directory.
        src = os.path.join(outputpath, "nvidia", nvidiadir, src_gpu, subdir, filename)
        dest = os.path.join(outputpath, "nvidia", nvidiadir, dest_gpu, subdir, filename)
        os.makedirs(os.path.join(outputpath, "nvidia", nvidiadir, src_gpu, subdir), exist_ok = True)
        symlink(dest, src, target_is_directory = False)
    else:
        # Directory symlinks can only be between GPU variants.
        if src_gpu[:2] != dest_gpu[:2]:
            raise MyException(f"Cannot link {src_gpu} to {dest_gpu}")

        # Set to True if the directory hierarchy also has Nouveau binaries in it
        # that might conflict.
        has_nouveau = nvidiadir == ""

        if has_nouveau and src_gpu.startswith(("tu", "ga")):
            src = os.path.join(outputpath, "nvidia", nvidiadir, src_gpu, subdir)
            dest = os.path.join(outputpath, "nvidia", nvidiadir, dest_gpu, subdir)
            os.makedirs(os.path.join(outputpath, "nvidia", nvidiadir, src_gpu), exist_ok = True)
        else:
            src = os.path.join(outputpath, "nvidia", nvidiadir, src_gpu)
            dest = os.path.join(outputpath, "nvidia", nvidiadir, dest_gpu)

            # If the source is an existing real directory, then create symlinks to
            # all the individual files in the target instead.  For some GPUs, the
            # script will create some unique files, and leave it to this function
            # to create symlinks for the rest.
            if os.path.isdir(src) and not os.path.islink(src):
                for d in os.listdir(os.path.join(dest, subdir)):
                    # Leave alone the files the source generated for itself
                    if not os.path.exists(os.path.join(src, subdir, d)):
                        link_gpu(dest_gpu, src_gpu, d)
                return

        symlink(dest, src, target_is_directory = True)

# Create symlinks in the target directory for the other GPUs.  This mirrors
# what the WHENCE file in linux-firmware does.
def symlinks():
    global outputpath
    global nvidiadir
    global subdir
    from pathlib import Path

    topdir = os.path.join(outputpath, "nvidia", nvidiadir)
    print(f"Creating symlinks in {topdir}")

    # Nouveau supports Turing and Ampere without GSP-RM support, using separate firmware
    # files in the 'acr', 'gr', 'nvdec', and 'sec2' subdirectories, which are all
    # siblings of the 'gsp' subdirectory.  Therefore, for these GPUs, we must symlink
    # from <gpu1>/gsp/ -> <gpu2>/gsp instead of just <gpu1> -> <gpu2>.

    # Turing / GA100
    for d in ["tu104", "tu106"]:
        link_gpu("tu102", d)

    for d in ["tu117"]:
        link_gpu("tu116", d)

    # TU11x uses the same GSP bootloader as TU10x
    link_gpu("tu102", "tu116", "gsp_bootloader.tlv")

    # TU11x and GA100 use the same generic bootloader as TU10x
    link_gpu("tu102", "tu116", "gen_bootloader.tlv")
    link_gpu("tu102", "ga100", "gen_bootloader.tlv")

    # Symlink the GSP-RM image for TU11x and GA100
    link_gpu("tu102", "tu116", "gsp.bin")
    link_gpu("tu102", "ga100", "gsp.bin")

    # Ampere
    for d in ["ga103", "ga104", "ga106", "ga107"]:
        link_gpu("ga102", d)

    # Ada
    for d in ["ad103", "ad104", "ad106", "ad107"]:
        link_gpu("ad102", d)

    # Blackwell
    for d in ["gb102"]:
        link_gpu("gb100", d)

    for d in ["gb203", "gb205", "gb206", "gb207"]:
        link_gpu("gb202", d)

    # Rubin
    if os.path.exists(os.path.join(topdir, "gr100")):
        for d in ["gr102"]:
            link_gpu("gr100", d)

    # Handle gsp.bin for all remaining paths.
    root = Path(topdir)
    paths = [d.name for d in root.glob("*")
             if os.path.isdir(os.path.join(topdir, d, subdir))
             and not os.path.exists(os.path.join(topdir, d, subdir, "gsp.bin"))]
    for d in paths:
        link_gpu("ga102", d, "gsp.bin")

    # Symlink the ucodes binaries, if they exist.
    if os.path.exists(os.path.join(topdir, "tu102", subdir, "ucodes.bin")):
        for d in ["tu116", "ga100"]:
            link_gpu("tu102", d, "ucodes.bin")
            link_gpu("tu102", d, "ucodes.tlv")

    if os.path.exists(os.path.join(topdir, "ga102", subdir, "ucodes.bin")):
        paths = [d.name for d in root.glob("*")
                 if os.path.isdir(os.path.join(topdir, d, subdir))
                 and not os.path.exists(os.path.join(topdir, d, subdir, "ucodes.bin"))
                 and d.name != "ga102"]
        for d in paths:
            link_gpu("ga102", d, "ucodes.bin")
            link_gpu("ga102", d, "ucodes.tlv")

    # Verify that there are no broken symlinks, and that every file
    # symlink points to a file inside a gsp/ directory.
    for dirpath, dirnames, filenames in os.walk(topdir):
        for name in dirnames + filenames:
            full = os.path.join(dirpath, name)
            if not os.path.islink(full):
                continue
            target = os.readlink(full)
            if not os.path.exists(full):
                print(f"Warning: broken symlink {full} -> {target}")
                continue
            # Directory symlinks (e.g. tu104/gsp -> ../tu102/gsp,
            # ad103 -> ad102) are exempt.
            if os.path.isdir(full):
                continue
            resolved = os.path.normpath(os.path.join(dirpath, target))
            if subdir and os.path.basename(os.path.dirname(resolved)) != subdir:
                print(f"Warning: symlink {full} -> {target} does not point to a file in a '{subdir}' directory")

    # Verify that we have the necessary files or links for every GPU.
    for d in [entry.name for entry in os.scandir(topdir) if entry.is_dir()]:
        if not os.path.exists(os.path.join(topdir, d, subdir, "gsp.bin")):
            print(f"Warning: {os.path.join(topdir, d, subdir, 'gsp.bin')} is missing")
        if not os.path.exists(os.path.join(topdir, d, subdir, "gsp.tlv")):
            print(f"Warning: {os.path.join(topdir, d, subdir, 'gsp.tlv')} is missing")
        if os.path.islink(os.path.join(topdir, d, subdir, "gsp.tlv")):
            print(f"Warning: {os.path.join(topdir, d, subdir, 'gsp.tlv')} should not be a symlink")
        if not os.path.exists(os.path.join(topdir, d, subdir, "gsp_bootloader.tlv")):
            print(f"Warning: {os.path.join(topdir, d, subdir, 'gsp_bootloader.tlv')} is missing")

        has_load = os.path.exists(os.path.join(topdir, d, subdir, "booter_load.tlv"))
        has_unload = os.path.exists(os.path.join(topdir, d, subdir, "booter_unload.tlv"))
        has_fmc = os.path.exists(os.path.join(topdir, d, subdir, "fmc.tlv"))
        if has_load != has_unload:
            print(f"Warning: {os.path.join(topdir, d, subdir)}/ booter_load requires booter_unload, and vice versa")
        if not has_load and not has_fmc:
            print(f"Warning: {os.path.join(topdir, d, subdir)}/ must have booter or fmc")
        if has_load and has_fmc:
            print(f"Warning: {os.path.join(topdir, d, subdir)}/ must not have both booter and fmc")

    # Verify that we have entries for each supported gpu
    for gpu in supported:
        if not os.path.exists(os.path.join(topdir, gpu, subdir, "gsp.bin")):
            print(f"Warning: {os.path.join(topdir, gpu, subdir, 'gsp.bin')} is missing")
        if not os.path.exists(os.path.join(topdir, gpu, subdir, "gsp.tlv")):
            print(f"Warning: {os.path.join(topdir, gpu, subdir, 'gsp.tlv')} is missing")
        if not os.path.exists(os.path.join(topdir, gpu, subdir, "gsp_bootloader.tlv")):
            print(f"Warning: {os.path.join(topdir, gpu, subdir, 'gsp_bootloader.tlv')} is missing")

        has_load = os.path.exists(os.path.join(topdir, gpu, subdir, "booter_load.tlv"))
        has_unload = os.path.exists(os.path.join(topdir, gpu, subdir, "booter_unload.tlv"))
        has_fmc = os.path.exists(os.path.join(topdir, gpu, subdir, "fmc.tlv"))
        if has_load != has_unload:
            print(f"Warning: {os.path.join(topdir, gpu, subdir)}/ booter_load requires booter_unload, and vice versa")
        if not has_load and not has_fmc:
            print(f"Warning: {os.path.join(topdir, gpu, subdir)}/ must have booter or fmc")
        if has_load and has_fmc:
            print(f"Warning: {os.path.join(topdir, gpu, subdir)}/ must not have both booter and fmc")

    # Verify that the gsp.tlv for each GPU has the correct TLV values for that GPU.  This
    # catches situations where one GPU is symlinked to another, but shouldn't be.
    for gpu in supported:
        filename = os.path.join(topdir, gpu, subdir, "gsp.tlv")
        if not os.path.exists(filename):
            continue

        entries = read_tlv(filename)
        for tag, field in hal_tlv_tags.items():
            if tag not in entries:
                print(f"Warning: {os.path.join(gpu, subdir, 'gsp.tlv')} has no '{tag}' entry")
                continue
            # Integer entries are written little-endian, as four or eight bytes
            # depending on magnitude.
            value = int.from_bytes(entries[tag], "little")
            if value != hal_value(field, gpu):
                print(f"Warning: {os.path.join(gpu, subdir, 'gsp.tlv')} tag {tag} value of {value} should be {hal_value(field, gpu)}")

# Create a text file that can be inserted as-is to the WHENCE file of the linux-firmware
# git repository.
#
# Traverse the outputpath and build a WHENCE file from it.  This ensures that WHENCE file
# always matches the real world.  The drawback is that it requires the -d and -s options
# to get a full picture.

# We must also maintain compatibility with the existing directory hierarchy that is
# defined by Nouveau, which is why ga103/gsp -> ga102/gsp, but ad103 -> ad102.
#
# Some hard rules for the layout of files:
#  1. No file of any version can symlink to a file of a different version,
#     even if the files are identical.  This allows distros to ship each version
#     independently.  Note that this does not really apply to TLV files, but
#     the restriction is still valid.
#  2. All files must be located in the /gsp/ subdirectory of the GPU directory,
#     and there must be no symlinks to any files outside of the /gsp/ directory.
#     This allows the Nova driver to find all of the files it needs inside
#     the /gsp/ directory.
#  3. Replacing a file/directory with a symlink (or vice versa) is strongly
#     discouraged.  Many distros cannot handle this transition.
#  4. Ideally, this file should only change when adding support for new GPUs,
#     because newer versions of firmware images should have the same filenames
#     as previous versions.
def whence():
    global outputpath

    whence = []
    for dirpath, dirnames, filenames in os.walk(os.path.join(outputpath, "nvidia")):  # followlinks=False by default
        # Regular files and symlinks-to-files both land in filenames
        for name in filenames:
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, outputpath)
            if os.path.islink(full):
                whence.append(f"Link: {rel} -> {os.readlink(full)}\n")
            else:
                whence.append(f"File: {rel}\n")
        # Symlinks-to-directories land in dirnames; with followlinks=False
        # os.walk lists them but won't recurse into them, so capture them here.
        for name in dirnames:
            full = os.path.join(dirpath, name)
            if os.path.islink(full):
                whence.append(f"Link: {os.path.relpath(full, outputpath)} -> {os.readlink(full)}\n")

    whence = sorted(whence, key=lambda s: s.split()[1])

    with open(os.path.join(outputpath, "WHENCE.txt"), "w") as f:
        f.writelines(whence)

    print(f"Created {os.path.join(outputpath, 'WHENCE.txt')}")

# ArgumentParser filter for alphanumeric parameters.
def alphanumeric(value: str) -> str:
    if not re.fullmatch(r"[A-Za-z0-9]*", value):
        raise argparse.ArgumentTypeError("must contain only alphanumeric characters")

    return value

def main():
    global outputpath
    global version
    global nvidiadir
    global subdir
    global hals

    parser = argparse.ArgumentParser(
        allow_abbrev = False,
        description = "Extract firmware binaries from the OpenRM git repository"
        " in a format expected by the Nova device drivers.",
        epilog = "Running as root and specifying -o /lib/firmware will install"
        " the firmware files directly where Nova expects them."
        " The --revision option is useful for testing new firmware"
        " versions without changing Nova source code."
        " The --driver option accepts a .run file path, a URL, or a local"
        " build output directory.  If -d is given with no argument, the .run"
        " file is downloaded automatically.")
    parser.add_argument("-i", "--input", default = os.getcwd(),
        help = "Path to source directory (where version.mk exists)")
    parser.add_argument("-o", "--output", default = None,
        help = "Path to target directory (where files will be written)")
    parser.add_argument("-r", "--revision",
        help = "Files will be named with this version number.")
    parser.add_argument("--debug-fused", action="store_true",
        help = "Extract debug instead of production images.")
    parser.add_argument("-d", "--driver",
        nargs = "?", const = "",
        help = "Also extract GSP-RM firmware from a source."
        " A URL or path to a .run driver package downloads or extracts it."
        " A path to a local build output directory (e.g."
        " drivers/resman/build/gsp/_out/Linux_amd64_release) copies"
        " the GSP firmware directly.  If -d is given with no argument,"
        " the .run file is downloaded automatically.")
    parser.add_argument("-s", "--symlink", action="store_true",
        help = "Also create symlinks for all supported GPUs.  Requires -d option.")
    parser.add_argument("-w", "--whence", action="store_true",
        help = "Also generate a WHENCE file.  Requires -d and -s options.")
    parser.add_argument("--nvidiadir", default = nvidiadir, type = alphanumeric,
        help = "Output directory top-level path, i.e. /lib/firmware/nvidia/{nvidiadir}/<gpu>/."
        " Default: '%(default)s'")
    parser.add_argument("--subdir", default = subdir, type = alphanumeric,
        help = "Output directory bottom-level path, i.e. /lib/firmware/nvidia/.../<gpu>/{subdir}."
        " Default: '%(default)s'")

    # Undocumented, dangerous option. If set, this will blindly erase the target directory.
    # For example, `-o /lib/firmware --clean` will trash your /lib/firmware and make your system
    # unbootable.  For safety, this requires the -o option.
    parser.add_argument("--clean", action = "store_true", help = argparse.SUPPRESS)

    args = parser.parse_args()

    if args.symlink and args.driver is None:
        parser.error("-s/--symlink requires -d/--driver")
    if args.whence and (args.driver is None or not args.symlink):
        parser.error("-w/--whence requires both -d/--driver and -s/--symlink")

    if args.clean and args.output is None:
        parser.error("--clean requires -o/--output")

    outputpath = os.path.abspath(args.output or os.path.join(os.getcwd(), "_out"))

    # Symlinks should not be created in the linux-firmware git repository, because
    # it uses the WHENCE file to create symlinks.  Check for that, to avoid
    # accidental usage that is confusing.
    if args.symlink and os.path.exists(os.path.join(outputpath, "copy-firmware.sh")):
        raise MyException("Symlinks should not be created in the linux-firmware repository")

    # If args.driver is a file or path, normalize it before the chdir.
    if args.driver and not re.search("^https?://", args.driver):
        args.driver = os.path.abspath(args.driver)

    args.input = os.path.abspath(args.input)
    os.chdir(args.input)

    if not os.path.isfile("version.mk"):
        raise MyException(f"Source directory {args.input} is incorrect")

    version = args.revision
    if not version:
        with open("version.mk") as f:
            m = re.search(r"^NVIDIA_VERSION = ([^\s]+)", f.read(), re.MULTILINE)
            if not m:
                raise MyException("Could not find or parse NVIDIA_VERSION from version.mk")
            version = m.group(1)

    if not version.isascii():
        raise MyException(f"Version string {version} must not contain non-ASCII characters")

    nvidiadir = args.nvidiadir
    subdir = args.subdir

    print(f"Generating files for version {version}")

    print(f"Writing files to {outputpath}")
    if os.path.isdir(outputpath) and os.listdir(outputpath):
        print("Warning: directory already exists and is not empty")

    if args.clean:
        # Aggressively try to delete the output directory.
        try:
            os.remove(outputpath)
        except OSError:
            pass
        shutil.rmtree(outputpath, ignore_errors = True)

        if os.path.lexists(outputpath):
            raise MyException(f"Could not delete {outputpath}")

    os.makedirs(outputpath, exist_ok = True)

    # GB10B (Jetson Thor) support was added in r580
    if is_supported("gb10b"):
        supported.append("gb10b")

    # GB20B (N1X) support was added in r580
    if is_supported("gb20b"):
        supported.append("gb20b")

    # GR100 support was added in r610
    if is_supported("gr100"):
        supported.extend(["gr100", "gr102"])

    # The generic bootloader is only defined for TU102 but is used
    # by all TU1xx and GA100.
    generic_bootloader("tu102")

    booter("tu102", "load", 16, args.debug_fused)
    booter("tu102", "unload", 16, args.debug_fused)
    # TU10x and GA100 do not have debug-fused versions of the GSP bootloader
    gsp_bootloader("tu102")

    booter("tu116", "load", 16, args.debug_fused)
    booter("tu116", "unload", 16, args.debug_fused)
    # TU11x uses the same bootloader as TU10x

    booter("ga100", "load", 384, args.debug_fused)
    booter("ga100", "unload", 384, args.debug_fused)
    gsp_bootloader("ga100")

    booter("ga102", "load", 384, args.debug_fused)
    booter("ga102", "unload", 384, args.debug_fused)
    gsp_bootloader("ga102", args.debug_fused)

    booter("ad102", "load", 384, args.debug_fused)
    booter("ad102", "unload", 384, args.debug_fused)
    gsp_bootloader("ad102", args.debug_fused)
#    scrubber("ad102", 384, args.debug_fused) # Not currently used by Nova

    gsp_bootloader("gh100", args.debug_fused)
    fmc("gh100", args.debug_fused)

    gsp_bootloader("gb100", args.debug_fused)
    fmc("gb100", args.debug_fused)

    gsp_bootloader("gb202", args.debug_fused)
    fmc("gb202", args.debug_fused)

    if "gb10b" in supported:
        gsp_bootloader("gb10b", args.debug_fused)
        fmc("gb10b", args.debug_fused)

    if "gb20b" in supported:
        gsp_bootloader("gb20b", args.debug_fused)
        fmc("gb20b", args.debug_fused)

    if "gr100" in supported:
        gsp_bootloader("gr100", args.debug_fused)
        fmc("gr100", args.debug_fused)

    # Extract gsp.bin and create gsp.tlv
    if args.driver is not None:
        # We only need to read the HALs if we're generating gsp.tlv

        # Search for the new NVoC variables, which were added in r630.
        # This may pick up variables we don't care about, depending
        # on the OpenRM version.
        # Note: g_gpu_arch_nvoc.c was added in r580
        hals2 = parse_nvoc_hals("src/nvidia/generated/g_gpu_arch_nvoc.c", hals)
        if "gspFwHeapBaseSize" in hals2:
            print("Generating GSP-RM TLV variables from NVOC source files")
            update_hals(hals2)
        else:
            # For older versions of OpenRM, scrape other files to build the
            # variables so that they mimic what g_gpu_arch_nvoc.c would
            # contain if it were complete.
            hals2 = parse_legacy_hals()
            if hals2:
                print("Generating GSP-RM TLV variables from legacy source files")
                update_hals(hals2)

        # print_hals(hals)
        driver(args.driver)

    if args.symlink:
        symlinks()

    if args.whence:
        whence()

if __name__ == "__main__":
    try:
        main()
    except MyException as e:
        # The full stack trace is too noisy with MyException
        print(f"Error: {e}", file=sys.stderr)

        # os._exit() reports the failure without raising SystemExit the way sys.exit()
        # would, but it also skips the flush that the interpreter would otherwise do on
        # the way out.  Stdout is block buffered whenever it is not a terminal, so it has
        # to be flushed by hand or a redirected run loses the output leading up to the
        # failure.
        #
        # The flush can itself fail, on a broken pipe from something like "| head" or on a
        # full disk.  That exception would escape this handler, burying the message above
        # in a traceback and exiting 120 rather than 1.  Ignore all of them rather than
        # just OSError, because the response is the same whatever the reason: if the
        # output cannot be written then there is nothing left to report it with, and the
        # process is about to exit non-zero regardless.
        try:
            sys.stdout.flush()
            sys.stderr.flush()
        except:
            pass

        os._exit(1)
